In [30]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [2]:
import pandas as pd

url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'

tables = pd.read_html(url)

sp500_table = tables[0]
sp500_table

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
499,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
500,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
501,ZION,Zions Bancorporation,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,1873
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [6]:
sp500_tickers = sp500_table['Symbol']
sp500_tickers

0       MMM
1       AOS
2       ABT
3      ABBV
4       ACN
       ...
498     YUM
499    ZBRA
500     ZBH
501    ZION
502     ZTS
Name: Symbol, Length: 503, dtype: object

In [16]:
import yfinance as yf

def get_sp500_market_cap(sp500_tickers):
    market_caps = dict()
    
    for ticker in sp500_tickers:
        try:
            info = yf.Ticker(ticker).info
            symbol = info['symbol']
            market_cap = info['marketCap']
            market_caps[symbol] = market_cap
        except Exception as e:
            print(f'Error fetching data for {ticker}: {e}')
    
    return market_caps

sp500_market_caps = get_sp500_market_cap(sp500_tickers)

for symbol, market_cap in sp500_market_caps:
    print(f'{symbol}: {market_cap}')

Error fetching data for BRK.B: 'marketCap'
Error fetching data for BF.B: 'marketCap'

ValueError: too many values to unpack (expected 2)

In [20]:
sp500_market_caps['BRK.B'] = 787310000000
sp500_market_caps['BF.B'] = 26500000000

print(len(sp500_market_caps))

for symbol, market_cap in sp500_market_caps.items():
    print(f'{symbol}: {market_cap}')

503
MMM: 56877604864
AOS: 11437310976
ABT: 181887877120
ABBV: 258068971520
ACN: 211915128832
ADM: 39224840192
ADBE: 272893165568
ADP: 95015567360
AES: 12033300480
AFL: 47697100800
A: 37780271104
ABNB: 88024776704
APD: 58269605888
AKAM: 17433841664
ALK: 4740521984
ALB: 14022509568
ARE: 21405605888
ALGN: 16654684160
ALLE: 9254568960
LNT: 13151926272
ALL: 36301221888
GOOGL: 1645697564672
GOOG: 1646103101440
MO: 73177890816
AMZN: 1504913522688
AMCR: 13593422848
AMD: 192729153536
AEE: 20538634240
AAL: 8937172992
AEP: 41907060736
AXP: 123136212992
AIG: 46053822464
AMT: 98887581696
AWK: 25771153408
AMP: 35760136192
AME: 36063498240
AMGN: 144666640384
APH: 55247945728
ADI: 90348216320
ANSS: 24548081664
AON: 63497502720
APA: 10474455040
AAPL: 3002079117312
AMAT: 122307043328
APTV: 23078711296
ACGL: 29775394816
ANET: 67519590400
AJG: 51814322176
AIZ: 8939876352
T: 121300090880
ATO: 16909240320
ADSK: 47197134848
AZO: 47126720512
AVB: 25106831360
AVY: 15576766464
AXON: 17517275136
BKR: 32322037760
BALL: 18139265024
BAC: 246631399424
BBWI: 8332704256
BAX: 18218104832
BDX: 67713732608
WRB: 18649303040
BBY: 16268859392
BIO: 9106158592
TECH: 10453714944
BIIB: 34053203968
BLK: 111281414144
BX: 140595757056
BK: 37046247424
BA: 144061595648
BKNG: 109937377280
BWA: 7741536768
BXP: 10062208000
BSX: 80200327168
BMY: 101605736448
AVGO: 472671911936
BR: 22862342144
BRO: 20909416448
BG: 15216738304
CHRW: 9973660672
CDNS: 70626213888
CZR: 9532269568
CPT: 10048752640
CPB: 12878104576
COF: 44273463296
CAH: 26118213632
KMX: 10576808960
CCL: 23068551168
CARR: 44620517376
CTLT: 6976526336
CAT: 130982486016
CBOE: 18631688192
CBRE: 25175900160
CDW: 28139636736
CE: 15444347904
COR: 40112553984
CNC: 39514849280
CNP: 17977260032
CDAY: 10469876736
CF: 14151518208
CRL: 10358106112
SCHW: 114631163904
CHTR: 54397579264
CVX: 268551307264
CMG: 60911861760
CB: 91524399104
CHD: 23088457728
CI: 75203338240
CINF: 15981079552
CTAS: 56031920128
CSCO: 195026714624
C: 93091127296
CFG: 13884121088
CLX: 17692053504
CME: 76790104064
CMS: 16785182720
KO: 253092413440
CTSH: 35347111936
CL: 63770161152
CMCSA: 168791736320
CMA: 6431446016
CAG: 14035529728
COP: 131006955520
ED: 31352881152
STZ: 43317751808
CEG: 36353658880
COO: 16895393792
CPRT: 45368225792
GLW: 24643958784
CTVA: 31163117568
CSGP: 34365788160
COST: 268708347904
CTRA: 18635556864
CCI: 51290226688
CSX: 66012622848
CMI: 32784908288
CVS: 94323326976
DHI: 44758274048
DHR: 162933391360
DRI: 19450124288
DVA: 9604328448
DE: 105575399424
DAL: 25339764736
XRAY: 6886509568
DVN: 27707072512
DXCM: 45323784192
FANG: 26239791104
DLR: 42546933760
DFS: 25670955008
DIS: 168645689344
DG: 29638037504
DLTR: 27517235200
D: 39300169728
DPZ: 13751659520
DOV: 20093800448
DOW: 36002709504
DTE: 22000617472
DUK: 71583727616
DD: 30567385088
EMN: 10020867072
ETN: 90824777728
EBAY: 21861318656
ECL: 54273548288
EIX: 25595559936
EW: 42188136448
EA: 36735377408
ELV: 112168632320
LLY: 560195567616
EMR: 50160246784
ENPH: 14971452416
ETR: 21248806912
EOG: 69598953472
EPAM: 15122723840
EQT: 15320059904
EFX: 27732451328
EQIX: 76374147072
EQR: 22282262528
ESS: 15019198464
EL: 49025040384
ETSY: 9819171840
EG: 16811827200
EVRG: 11786984448
ES: 21088811008
EXC: 38717521920
EXPE: 19353536512
EXPD: 17445951488
EXR: 30199963648
XOM: 396339707904
FFIV: 10196496384
FDS: 16854927360
FICO: 27769190400
FAST: 35342028800
FRT: 8199696896
FDX: 67066286080
FITB: 20971919360
FSLR: 15976383488
FE: 21300011008
FIS: 35780108288
FI: 78540341248
FLT: 18232979456
FMC: 6906595840
F: 43191828480
FTNT: 40436604928
FTV: 24212043776
FOXA: 13723402240
FOX: 13736020992
BEN: 12698443776
FCX: 52427603968
GRMN: 24029259776
IT: 34847858688
GEHC: 30965626880
GEN: 14358423552
GNRC: 7740381696
GD: 68521705472
GE: 131118350336
GIS: 38370226176
GM: 45802254336
GPC: 19177545728
GILD: 99072647168
GL: 11579894784
GPN: 31220639744
GS: 112404283392
HAL: 31443179520
HIG: 23553296384
HAS: 6714789888
HCA: 67466629120
PEAK: 10202929152
HSIC: 9210005504
HSY: 38738055168
HES: 42022424576
HPE: 20512931840
HLT: 43234500608
HOLX: 16591407104
HD: 325032640512
HON: 130525110272
HRL: 17249673216
HST: 12674161664
HWM: 21591855104
HPQ: 28284260352
HUBB: 16293579776
HUM: 60240674816
HBAN: 17174227968
HII: 9608717312
IBM: 146683428864
IEX: 15403402240
IDXX: 43714256896
ITW: 74601676800
ILMN: 18574835712
INCY: 12378659840
IR: 29052278784
PODD: 13574484992
INTC: 176608231424
ICE: 64722927616
IFF: 19525015552
IP: 12736885760
IPG: 12024411136
INTU: 159695077376
ISRG: 109566558208
IVZ: 6792760320
INVH: 20401301504
IQV: 39576948736
IRM: 19312220160
JBHT: 19368192000
JKHY: 12065447936
J: 16211727360
JNJ: 377918914560
JCI: 37499236352
JPM: 454553501696
JNPR: 9220068352
K: 18564583424
KVUE: 37924397056
KDP: 44663119872
KEY: 12400762880
KEYS: 24773120000
KMB: 41103761408
KIM: 12670348288
KMI: 39087407104
KLAC: 72934309888
KHC: 44468211712
KR: 32023947264
LHX: 37642645504
LH: 18536216576
LRCX: 91957870592
LW: 14656467968
LVS: 34067347456
LDOS: 15111221248
LEN: 38280409088
LIN: 193708687360
LYV: 19166492672
LKQ: 12167681024
LMT: 111126650880
L: 15549432832
LOW: 120166998016
LULU: 58308829184
LYB: 30214320128
MTB: 22097573888
MRO: 13908335616
MPC: 54809264128
MKTX: 9930552320
MAR: 60341755904
MMC: 95434088448
MLM: 28507953152
MAS: 14279857152
MA: 384600702976
MTCH: 8943973376
MKC: 18104383488
MCD: 207230222336
MCK: 60578471936
MDT: 104676564992
MRK: 267744575488
META: 823640129536
MET: 47357358080
MTD: 23889909760
MGM: 13627454464
MCHP: 45983412224
MU: 81543569408
MSFT: 2747632189440
MAA: 15317309440
MRNA: 31337732096
MHK: 5982305792
MOH: 20929699840
TAP: 13344914432
MDLZ: 96549044224
MPWR: 27145981952
MNST: 56048500736
MCO: 68717297664
MS: 132223926272
MOS: 11545446400
MSI: 53495635968
MSCI: 41448136704
NDAQ: 32361965568
NTAP: 18563393536
NFLX: 197419941888
NEM: 45869101056
NWSA: 12704169984
NWS: 12705227776
NEE: 122117775360
NKE: 177515577344
NI: 10831473664
NDSN: 13754178560
NSC: 50968793088
NTRS: 17113596928
NOC: 72386666496
NCLH: 7938430464
NRG: 10802806784
NUE: 40145510400
NVDA: 1145709527040
NVR: 20461541376
NXPI: 54024548352
ORLY: 58033827840
OXY: 49930240000
ODFL: 40562298880
OMC: 16309325824
ON: 32018085888
OKE: 40230969344
ORCL: 309686927360
OTIS: 35335421952
PCAR: 49482989568
PKG: 14771878912
PANW: 92373442560
PARA: 10300124160
PH: 55842734080
PAYX: 44630216704
PAYC: 10623870976
PYPL: 64952545280
PNR: 11037014016
PEP: 229752864768
PFE: 164773543936
PCG: 43506737152
PM: 141409026048
PSX: 55408058368
PNW: 8567785984
PXD: 52053569536
PNC: 56277614592
POOL: 14070719488
PPG: 33849090048
PPL: 19235250176
PFG: 17890437120
PG: 344282726400
PGR: 94442397696
PLD: 110368333824
PRU: 35609038848
PEG: 31221862400
PTC: 19273570304
PSA: 47424716800
PHM: 20092377088
QRVO: 9599269888
PWR: 27708753920
QCOM: 145324408832
DGX: 15177601024
RL: 8441729024
RJF: 22093568000
RTX: 118957613056
O: 40163373056
REG: 11971421184
REGN: 91414159360
RF: 16197083136
RSG: 50560593920
RMD: 24314308608
RVTY: 11294825472
RHI: 8768635904
ROK: 31963951104
ROL: 19995611136
ROP: 57064312832
ROST: 44966940672
RCL: 30422808576
SPGI: 133170044928
CRM: 243602046976
SBAC: 27450769408
SLB: 70451650560
STX: 16535995392
SEE: 4734611968
SRE: 45626281984
NOW: 142324531200
SHW: 73802670080
SPG: 49613803520
SWKS: 16278620160
SJM: 12504824832
SNA: 14853348352
SEDG: 4748280320
SO: 77690314752
LUV: 16932646912
SWK: 14349910016
SBUX: 109833641984
STT: 22458742784
STLD: 18662240256
STE: 19732375552
SYK: 109102989312
SYF: 14319687680
SNPS: 80840491008
SYY: 37000728576
TMUS: 178907447296
TROW: 22577016832
TTWO: 26856286208
TPR: 7498966016
TRGP: 19242829824
TGT: 61622644736
TEL: 40966889472
TDY: 19173029888
TFX: 10703996928
TER: 14161181696
TSLA: 777849929728
TXN: 143432663040
TXT: 15070823424
TMO: 191373918208
TJX: 101044035584
TSCO: 22726643712
TT: 52625969152
TDG: 53223227392
TRV: 41785597952
TRMB: 11637366784
TFC: 45031366656
TYL: 17260390400
TSN: 17666084864
USB: 62085775360
UDR: 12438351872
ULTA: 24089417728
UNP: 142033289216
UAL: 13592941568
UPS: 132082606080
URI: 32450344960
UNH: 507080867840
UHS: 9255468032
VLO: 41802522624
VTR: 18670479360
VLTO: 18600564736
VRSN: 22084231168
VRSK: 33999454208
VZ: 162362343424
VRTX: 90763689984
VFC: 7262389760
VTRS: 11642797056
VICI: 31587717120
V: 523786485760
VMC: 28334501888
WAB: 21232134144
WBA: 18474821632
WMT: 414980308992
WBD: 27007162368
WM: 69659934720
WAT: 17148011520
WEC: 26487078912
WFC: 163569074176
WELL: 49103769600
WST: 25370327040
WDC: 15440451584
WRK: 10476758016
WY: 22870931456
WHR: 5980622336
WMB: 43818328064
WTW: 24888758272
GWW: 39918305280
WYNN: 9334421504
XEL: 33804247040
XYL: 25648287744
YUM: 34967023616
ZBRA: 12120352768
ZBH: 24137304064
ZION: 5647439360
ZTS: 83595476992
BRK.B: 787310000000
BF.B: 26500000000

In [22]:
sp500_df = pd.DataFrame(list(sp500_market_caps.items()), columns=['Symbol', 'Market_Capital'])

merged_df = pd.merge(sp500_table, sp500_df, on='Symbol')

merged_df

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded,Market_Capital
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902,56877604864
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916,11437310976
2,ABT,Abbott,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888,181887877120
3,ABBV,AbbVie,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888),258068971520
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989,211915128832
...,...,...,...,...,...,...,...,...,...
498,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997,34967023616
499,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969,12120352768
500,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927,24137304064
501,ZION,Zions Bancorporation,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,1873,5647439360
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952,83595476992

In [37]:
merged_df = merged_df.sort_values('Ticker')
merged_df.to_csv('Details_sp500.csv')

In [31]:
merged_df['Market_Capital'].max()
merged_df.loc[merged_df['Market_Capital'] == 3002079117312]

3002079117312

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded,Market_Capital
42,AAPL,Apple Inc.,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193,1977,3002079117312

In [35]:
merged_df.rename(columns={'Symbol': 'Ticker'}, inplace=True)
merged_df

,Ticker,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded,Market_Capital
10,A,Agilent Technologies,Health Care,Health Care Equipment,"Santa Clara, California",2000-06-05,1090872,1999,37780271104
28,AAL,American Airlines Group,Industrials,Passenger Airlines,"Fort Worth, Texas",2015-03-23,6201,1934,8937172992
42,AAPL,Apple Inc.,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193,1977,3002079117312
3,ABBV,AbbVie,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888),258068971520
11,ABNB,Airbnb,Consumer Discretionary,"Hotels, Resorts & Cruise Lines","San Francisco, California",2023-09-18,1559720,2008,88024776704
...,...,...,...,...,...,...,...,...,...
498,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997,34967023616
500,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927,24137304064
499,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969,12120352768
501,ZION,Zions Bancorporation,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,1873,5647439360
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952,83595476992